### PR TITLE
Call spawn with absolute path if the file exists, or relative path if it doesn't

### LINKED ISSUE #695: Engines do not honor system paths on Linux
I use ssh to run my engines remotely on a more powerful machine.

For v0.43.3 and v0.50.0 I used "ssh" as my engine, works fine.
For v0.51.1 "ssh" doesn't work anymore, "/usr/bin/ssh" has to be specified.

Basically this is the same problem as pointed out in [issue 117](https://github.com/SabakiHQ/Sabaki/issues/117).

Sabaki version: v0.51.1
OS: Linux (SparkyLinux based on Debian testing branch, Kernel 5.6.0)

I think the issue has been introduced in [this commit](https://github.com/SabakiHQ/Sabaki/commit/f9bd1f30f63bd631064aff9f32f2d82a24491ac1).

### PR DESCRIPTION
**Pull request by ebifrier**
fix #695

### CODE REVIEW

File: src/modules/enginesyncer.js [hunk 1]
```diff
@@ -87,8 +88,19 @@ export default class EngineSyncer extends EventEmitter {
...
-    this.controller = new Controller(resolve(path), [...argvsplit(args)], {
-      cwd: dirname(resolve(path))
+    let fileExistsSync = path => {
+      try {
+        fs.accessSync(path, fs.F_OK)
+        return true
+      } catch {
+        return false
+      }
+    }
```
Comment (yishn) [inline src/modules/enginesyncer.js:98]: Why not simply use `fs.existsSync()`?

Comment (ebifrier) [reply src/modules/enginesyncer.js]: My understanding is that fs.existsSync is deprecated, but that information was outdated. I modified it to use fs.existsSync.

**Comment by yishn** [comment]
Thanks a lot for your PR!
